
import { AuthProvider } from "./Providers";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
const inter = Inter({ subsets: ["latin"] });
import Nav from "./components/Nav";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Nav/>
          {children}
          <Footer/>
        </AuthProvider>
      </body>
    </html>
  );
}
